import React from "react"
import figma from "@figma/code-connect/react"
import Button from "./Button"
import { buttonTokens, tokenToPx, tokenToColor, getTypographyValue } from "../../tokens"

/**
 * -- This file was auto-generated by Code Connect --
 * Maps Figma Button component to React Button component using Design Tokens from tokens.json
 */

figma.connect(
  Button,
  "https://www.figma.com/file/xGTfXooDmNwkKcrDJVWPdG/Code-connect?node-id=1-28",
  {
    props: {
      label: figma.string("Label"),
      variant: figma.enum("Variant", {
        Enabled: "Enabled",
        Hover: "Hover",
        Disabled: "Disabled",
      }),
      size: figma.enum("Size", {
        Small: "Small",
        Medium: "Medium",
        Large: "Large",
      }),
      // Design token props from Figma
      backgroundColor: figma.string("Background"),
      textColor: figma.string("Text"),
      borderColor: figma.string("Border"),
      borderRadius: figma.string("Border Radius"),
      padding: figma.string("Padding"),
      fontSize: figma.string("Font Size"),
    },
    example: (props: {
      label: string;
      variant?: "Enabled" | "Hover" | "Disabled";
      size?: "Small" | "Medium" | "Large";
      backgroundColor?: string;
      textColor?: string;
      borderColor?: string;
      borderRadius?: string;
      padding?: string;
      fontSize?: string;
    }) => {
      // Map Figma props to Button component props with design tokens
      const typography = getTypographyValue(buttonTokens.typography);
      
      return (
        <Button
          label={props.label}
          variant={props.variant || "Enabled"}
          size={props.size || "Medium"}
          backgroundColor={props.backgroundColor || buttonTokens.primary.background.enabled}
          textColor={props.textColor || buttonTokens.primary.textColor.enabled}
          borderColor={props.borderColor}
          borderRadius={props.borderRadius || buttonTokens.radius}
          padding={props.padding || `${tokenToPx(buttonTokens.padding.y.md)} ${tokenToPx(buttonTokens.padding.x.md)}`}
          fontSize={props.fontSize || typography.fontSize}
        />
      );
    },
  },
)
