import React from "react"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  "Button",
  "https://www.figma.com/file/xGTfXooDmNwkKcrDJVWPdG/Code-connect?node-id=1%3A28",
  {
    props: {
      state: figma.enum("State", {
        Enabled: "enabled",
        Hover: "focus",
        Disabled: "disabled",
      }),
    },
    example: (props) => <button {...props}>Button</button>,
  },
)
